services:
  coqui-tts-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coqui-tts-web
    ports:
      - "2201:2201"
    volumes:
      # Model cache - persists downloaded models
      - tts-models:/app/models
      # Voice profiles - persists cloned voices
      - tts-voices:/app/voices
      # Generated outputs - persists synthesized audio
      - tts-outputs:/app/outputs
      # Temporary uploads
      - tts-uploads:/app/uploads
    environment:
      - PORT=2201
      - TTS_MODELS_DIR=/app/models
      - TTS_VOICES_DIR=/app/voices
      - TTS_OUTPUTS_DIR=/app/outputs
      - TTS_UPLOADS_DIR=/app/uploads
      - PYTHONUNBUFFERED=1
      - TTS_HOME=/app/models
      - NUMBA_CACHE_DIR=/tmp/numba_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2201/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    labels:
      - "com.coqui.tts.description=Coqui TTS with Web GUI"
      - "com.coqui.tts.version=1.0.0"
      - "com.coqui.tts.author=jyoung2000"

volumes:
  tts-models:
    driver: local
  tts-voices:
    driver: local
  tts-outputs:
    driver: local
  tts-uploads:
    driver: local